name = "WorkshopComponents"
uuid = "a8f4153b-234a-49f2-adcf-bf0027f9e260"
authors = ["Marko Polic marko.polic@juliahub.com, JuliaHub Inc."]
version = "0.0.1"

[deps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
JuliaSimCompiler = "8391cb6b-4921-5777-4e45-fd9aab8cb88d"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
Render = ["Makie"]

[compat]
DynamicQuantities = "0.13"
JuliaSimCompiler = "0.1.17"
ModelingToolkit = "9"
PrecompileTools = "1"
RuntimeGeneratedFunctions = "0.5"
Test = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
